apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: {{ .Values.app.driver.name }}
  labels:
{{ include "cert-manager-csi.labels" . | indent 4 }}
spec:
  podInfoOnMount: true
  volumeLifecycleModes:
  - Ephemeral
